# Generated by Django 6.0.4 on 2026-05-27 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquete", "0002_alter_opcao_pergunta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pergunta",
            name="criado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perguntas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
